#!/usr/bin/env bash
# will display information about subdomains. 


print_infos () {
	echo -n "The subdomain $2 is a "
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}'
	echo -n " record and points to "
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}'
	echo ""
}
if [ $# -eq 2 ]
then
	print_infos "$1" "$2"
else
	for subd in "www" "lb-01" "web-01" "web-02"
	do
		print_infos "$1" "$subd"
	done
fi
