#!/usr/bin/env bash
# Setup a load balncer

sudo apt update
sudo apt install -y haproxy
sudo cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.save
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "frontend web80front
	bind *:80
	mode http
	default_backend web80back

backend web80back
	mode http
	server web-01 web-01.badreziani.tech check
	server web-02 web-02.badreziani.tech check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
