#!/usr/bin/env bash
# Setup a load balncer

sudo apt update
sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt install haproxy=2.9.\*
sudo apt update && sudo apt upgrade -y
sudo cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.save
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "frontend web80front
	bind *:80
	mode http
	default_backend web80back

backend web80back
	server web-01 52.201.221.254
	server web-02 54.234.42.193
	mode http
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
