#!/usr/bin/env bash
# runs nginx as nginx user

file=/etc/nginx/sites-available/default
sed -i 's/80 default_server/8080 default_server/' "$file"
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
service nginx restart
